### ISSUE TITLE
Where do I define REST

### ISSUE THREAD

**Issue by Choyka** [gunjandatta/sprest-jslink#1]
I am getting an Uncaught ReferenceError: $REST is not defined
Where do I define REST?

**Comment by gunjandatta** [comment]
If you look at the sample project, I've manually added the "dist" folder from the node_modules directory. This will ensure the ~site/node_modules/gd-sprest/dist/gd-sprest.min.js file is made available in the app web. I do not recommend doing this, as w/ later posts/examples I go into other methods to use webpack to bundle everything together.

To help you out, copy the gd-sprest.min.js file to the same location of where you uploaded the jslink file (customizeView.js) and make sure you reference both files. For example, let's say you uploaded both files to the root web site assets and placed them in a folder called jslinks. The JSLink property value would look like this:

~sitecollection/siteassets/jslinks/gd-sprest.min.js|~sitecollection/siteassets/jslinks/customizeView.js

I hope this helps you out. I'll close this out, but please re-open if you still have issues.
